---
- include_vars: "{{ansible_pkg_mgr}}.yml"


- name: add include to config
  lineinfile:
    path: "{{postgres_config_base}}/{{pgc.value.version}}/{{pgc.key}}/postgresql.conf"
    insertafter: EOF
    line: "include_dir = 'conf.d'"
  when: ansible_pkg_mgr == 'yum'
- name: create conf.d directory
  file:
    path: "{{postgres_config_base}}/{{pgc.value.version}}/{{pgc.key}}/conf.d"
    state: directory
    owner: postgres
    group: postgres

- name: add custom settings
  lineinfile:
    path: "{{postgres_config_base}}/{{pgc.value.version}}/{{pgc.key}}/conf.d/postgresql.custom.conf"
    create: yes
    owner: postgres
    group: postgres
    insertafter: EOF
    regexp: "^{{item.key}} ="
    line: "{{item.key}} = '{{item.value}}'"
  with_dict:
    - "{{pgc.value.settings}}"
