---
- include_vars: "{{ansible_pkg_mgr}}.yml"

# - name: remove insecure local,all,all hba configuration
#   postgresql_pg_hba:
#     dest: "{{pgc.value.data}}/pg_hba.conf"
#     contype: local
#     users: all
#     databases: all
#     state: absent
#
# - name: remove insecure host,all,all hba ipv4 configuration
#   postgresql_pg_hba:
#     dest: "{{pgc.value.data}}/pg_hba.conf"
#     contype: host
#     users: all
#     databases: all
#     source: '127.0.0.1/32'
#     state: absent
# - name: remove insecure host,all,all hba ipv6 configuration
#   postgresql_pg_hba:
#     dest: "{{pgc.value.data}}/pg_hba.conf"
#     contype: host
#     users: all
#     databases: all
#     source: '::1/128'
#     state: absent

# - name: add hba rules for local postgres user
#   postgresql_pg_hba:
#     dest: "{{pgc.value.data}}/pg_hba.conf"
#     contype: local
#     users: postgres
#     databases: all
#     method: ident
#     state: present

- name: add hba rules for local postgres user
  postgresql_pg_hba:
    dest: "{{postgres_config_base}}/{{pgc.value.version}}/{{pgc.key}}/pg_hba.conf"
    contype: host
    users: postgres
    databases: all
    source: samehost
    method: md5
    state: present



#
# - name: replication access
#   postgresql_pg_hba:
#     dest: "{{pgc.value.data}}/pg_hba.conf"
#     contype: host
#     users: replication
#     source: samenet
#     databases: replication
#     method: md5
#     create: true
#     state: present
# - name: replication access
#   postgresql_pg_hba:
#     dest: "{{pgc.value.data}}/pg_hba.conf"
#     contype: host
#     users: replication
#     source: 10.54.248.0/24
#     databases: replication
#     method: md5
#     create: true
#     state: present
