---
- name: make fs
  filesystem:
    fstype: "{{item.value.fstype}}"
    dev: "{{item.value.dev}}"
  with_dict:
    - "{{postgres_mounts}}"
  when: postgres_mounts is defined

- name: mount fs
  mount:
    path: "{{item.key}}"
    fstype: "{{item.value.fstype}}"
    src: "{{item.value.dev}}"
    opts: "defaults,noatime"
    state: mounted
  with_dict:
    - "{{postgres_mounts}}"
  when: postgres_mounts is defined

- name: create directories
  file:
    path: "{{item.key}}"
    state: directory
    owner: postgres
    group: postgres
    mode: 0700
  with_dict:
    - "{{postgres_mounts}}"
  when: postgres_mounts is defined
