---

- name: OS user config | shell profile
  template:
    src: profile.j2
    dest: "{{postgres_data_base}}/.pgsql_profile"
    owner: postgres
    group: postgres

- name: "OS user config | env file"
  template:
    src: pgenv.j2
    dest: "{{postgres_data_base}}/{{pgc.key}}.env"
    owner: postgres
    group: postgres
  with_dict:
      - "{{postgres_cluster}}"
  loop_control:
      loop_var: pgc

- name: OS user config | add psqlrc
  copy:
    src: psqlrc
    dest: "{{postgres_data_base}}/.psqlrc"
    owner: postgres
    group: postgres
