---

- name: "pgbackrest | configure retention"
  ini_file:
    path: /etc/pgbackrest.conf
    section: "{{item.value.stanza}}"
    option: "repo1-retention-full"
    value: "{{item.value.backup_retention | default(2)}}"
  with_dict:
    - "{{postgres_cluster}}"

- name: "pgbackrest | configure path"
  ini_file:
    path: /etc/pgbackrest.conf
    section: "{{item.value.stanza}}"
    option: "pg1-path"
    value: "{{postgres_data_base}}/{{item.value.version}}/{{item.key}}"
  with_dict:
    - "{{postgres_cluster}}"

- name: "pgbackrest | create stanza"
  shell: "pgbackrest --stanza {{item.value.stanza}} stanza-create"
  args:
    creates: "/var/lib/pgbackrest/backup/{{item.value.stanza}}"
  become: true
  become_user: postgres
  with_dict:
    - "{{postgres_cluster}}"
  when: inventory_hostname == postgres_primary
